@tool
class_name LubanConfigNameGenerator
extends RefCounted


const defaultConfigDirectory: String = "res://Game/Cd_ProjectZero/Assets/Configs/GameConfigs"
const defaultOutputScriptPath: String = "res://Game/Cd_ProjectZero/Scripts/Gameplay/Config/TbCfg.gd"
const defaultClassName: String = "TbCfg"
const defaultAutoGenDirectory: String = "res://Game/Cd_ProjectZero/Scripts/Mono/Luban/Configs/AutoGen"
const defaultFieldOutputScriptPath: String = "res://Game/Cd_ProjectZero/Scripts/Gameplay/Config/TbField.gd"
const defaultFieldClassName: String = "TbField"
const configFileExtension: String = "bytes"
const csharpFileExtension: String = "cs"


static func generate(
	configDirectory: String = defaultConfigDirectory,
	outputScriptPath: String = defaultOutputScriptPath,
	className: String = defaultClassName,
	autoGenDirectory: String = defaultAutoGenDirectory,
	fieldOutputScriptPath: String = defaultFieldOutputScriptPath,
	fieldClassName: String = defaultFieldClassName
) -> bool:
	var configNames: PackedStringArray = getConfigNames(configDirectory)
	if configNames.is_empty():
		push_error("No Luban config data files found in: %s" % configDirectory)
		return false

	configNames.sort()
	var scriptText: String = createScriptText(configNames, configDirectory, className)
	if not ensureOutputDirectory(outputScriptPath):
		return false

	if not writeTextFile(outputScriptPath, scriptText, "Luban config names"):
		return false

	if not generateFieldNames(configNames, autoGenDirectory, fieldOutputScriptPath, fieldClassName):
		return false

	print("Generated Luban config names: %s (%s configs)" % [outputScriptPath, configNames.size()])
	return true


static func getConfigNames(configDirectory: String = defaultConfigDirectory) -> PackedStringArray:
	var names: PackedStringArray = []
	var directory: DirAccess = DirAccess.open(configDirectory)
	if directory == null:
		push_error("Cannot open Luban config directory: %s" % configDirectory)
		return names

	directory.list_dir_begin()
	var fileName: String = directory.get_next()
	while not fileName.is_empty():
		if not directory.current_is_dir() and fileName.get_extension().to_lower() == configFileExtension:
			names.append(fileName.get_basename())
		fileName = directory.get_next()
	directory.list_dir_end()
	return names


static func createScriptText(configNames: PackedStringArray, configDirectory: String, className: String) -> String:
	var usedConstantNames: Dictionary = {}
	var constantLines: Array[String] = []
	var allNameLines: Array[String] = []

	for configName: String in configNames:
		var constantName: String = createUniqueConstantName(configName, usedConstantNames)
		constantLines.append("const %s: StringName = &\"%s\"" % [constantName, configName])
		allNameLines.append("\t%s," % constantName)

	var lines: Array[String] = [
		"# This file is generated by LubanConfigNameGenerator.gd.",
		"# Source: %s" % configDirectory,
		"# Do not edit manually.",
		"",
		"class_name %s" % className,
		"extends RefCounted",
		"",
	]
	lines.append_array(constantLines)
	lines.append("")
	lines.append("const allConfigNames: Array[StringName] = [")
	lines.append_array(allNameLines)
	lines.append("]")
	lines.append("")
	lines.append("")
	lines.append("static func hasConfigName(configName: StringName) -> bool:")
	lines.append("\treturn configName in allConfigNames")
	lines.append("")
	return "\n".join(lines)


static func generateFieldNames(configNames: PackedStringArray, autoGenDirectory: String, fieldOutputScriptPath: String, fieldClassName: String) -> bool:
	var csharpFiles: PackedStringArray = findFilesRecursive(autoGenDirectory, csharpFileExtension)
	if csharpFiles.is_empty():
		push_error("No Luban C# AutoGen files found in: %s" % autoGenDirectory)
		return false

	var fileByBaseName: Dictionary = createFileLookup(csharpFiles)
	var tableFieldInfos: Array[Dictionary] = []

	for configName: String in configNames:
		var tableClassName: String = getTableClassName(configName, fileByBaseName)
		if tableClassName.is_empty():
			push_warning("Cannot find Luban table class for config: %s" % configName)
			continue

		var tableFilePath: String = String(fileByBaseName[tableClassName.to_lower()])
		var tableScriptText: String = readTextFile(tableFilePath)
		var rowClassName: String = getRowClassName(tableScriptText)
		if rowClassName.is_empty():
			push_warning("Cannot find Luban row class for table: %s" % tableClassName)
			continue

		var rowFileKey: String = rowClassName.to_lower()
		if not fileByBaseName.has(rowFileKey):
			push_warning("Cannot find Luban row file for class: %s" % rowClassName)
			continue

		var rowFilePath: String = String(fileByBaseName[rowFileKey])
		var rowScriptText: String = readTextFile(rowFilePath)
		var fieldNames: PackedStringArray = getRowFieldNames(rowScriptText)
		if fieldNames.is_empty():
			push_warning("Cannot find Luban row fields for class: %s" % rowClassName)
			continue

		tableFieldInfos.append({
			"configName": configName,
			"className": createFieldInnerClassName(configName),
			"fieldNames": fieldNames,
		})

	if tableFieldInfos.is_empty():
		push_error("No Luban field names could be generated from: %s" % autoGenDirectory)
		return false

	var scriptText: String = createFieldScriptText(tableFieldInfos, autoGenDirectory, fieldClassName)
	if not ensureOutputDirectory(fieldOutputScriptPath):
		return false

	if not writeTextFile(fieldOutputScriptPath, scriptText, "Luban field names"):
		return false

	print("Generated Luban field names: %s (%s tables)" % [fieldOutputScriptPath, tableFieldInfos.size()])
	return true


static func createFieldScriptText(tableFieldInfos: Array[Dictionary], autoGenDirectory: String, fieldClassName: String) -> String:
	var lines: Array[String] = [
		"# This file is generated by LubanConfigNameGenerator.gd.",
		"# Source: %s" % autoGenDirectory,
		"# Do not edit manually.",
		"",
		"class_name %s" % fieldClassName,
		"extends RefCounted",
		"",
	]

	for tableInfo: Dictionary in tableFieldInfos:
		var configName: String = String(tableInfo["configName"])
		var className: String = String(tableInfo["className"])
		var fieldNames: PackedStringArray = tableInfo["fieldNames"]
		var usedConstantNames: Dictionary = {}
		var allFieldLines: Array[String] = []

		lines.append("class %s:" % className)
		lines.append("\tconst table: StringName = &\"%s\"" % configName)

		for fieldName: String in fieldNames:
			var constantName: String = createUniqueName(sanitizeConstantName(fieldName), usedConstantNames)
			lines.append("\tconst %s: StringName = &\"%s\"" % [constantName, fieldName])
			allFieldLines.append("\t\t%s," % constantName)

		lines.append("")
		lines.append("\tconst allFieldNames: Array[StringName] = [")
		lines.append_array(allFieldLines)
		lines.append("\t]")
		lines.append("")
		lines.append("")
		lines.append("\tstatic func hasFieldName(fieldName: StringName) -> bool:")
		lines.append("\t\treturn fieldName in allFieldNames")
		lines.append("")

	return "\n".join(lines)


static func createUniqueConstantName(configName: String, usedConstantNames: Dictionary) -> String:
	var baseName: String = sanitizeConstantName(createFriendlyConfigName(configName))
	return createUniqueName(baseName, usedConstantNames)


static func createUniqueName(baseName: String, usedNames: Dictionary) -> String:
	var constantName: String = baseName
	var suffix: int = 2
	while usedNames.has(constantName):
		constantName = "%s_%s" % [baseName, suffix]
		suffix += 1
	usedNames[constantName] = true
	return constantName


static func createFieldInnerClassName(configName: String) -> String:
	var constantName: String = sanitizeConstantName(createFriendlyConfigName(configName))
	var className: String = constantName.substr(0, 1).to_upper() + constantName.substr(1, constantName.length() - 1)
	if not className.is_valid_identifier() or className.substr(0, 1).is_valid_int():
		className = "Table%s" % className.md5_text()
	return className


static func getTableClassName(configName: String, fileByBaseName: Dictionary) -> String:
	var parts: PackedStringArray = configName.split("_", false)
	if parts.is_empty():
		return ""

	var tableFileKey: String = parts[parts.size() - 1].to_lower()
	if fileByBaseName.has(tableFileKey):
		return String(fileByBaseName[tableFileKey]).get_file().get_basename()

	return ""


static func getRowClassName(tableScriptText: String) -> String:
	var listMatch: RegExMatch = searchRegex(tableScriptText, "List<([A-Za-z0-9_\\.]+)>")
	if listMatch != null:
		return listMatch.get_string(1).get_slice(".", listMatch.get_string(1).get_slice_count(".") - 1)

	var dataMatch: RegExMatch = searchRegex(tableScriptText, "private\\s+readonly\\s+([A-Za-z0-9_\\.]+)\\s+_data")
	if dataMatch != null:
		return dataMatch.get_string(1).get_slice(".", dataMatch.get_string(1).get_slice_count(".") - 1)

	return ""


static func getRowFieldNames(rowScriptText: String) -> PackedStringArray:
	var fieldNames: PackedStringArray = []
	var regex: RegEx = RegEx.new()
	var error: Error = regex.compile("public\\s+readonly\\s+[A-Za-z0-9_<>,\\.\\?\\[\\]\\s]+\\s+([A-Za-z_][A-Za-z0-9_]*)\\s*;")
	if error != OK:
		push_error("Cannot compile Luban row field regex.")
		return fieldNames

	for regexMatch: RegExMatch in regex.search_all(rowScriptText):
		fieldNames.append(regexMatch.get_string(1))

	return fieldNames


static func searchRegex(text: String, pattern: String) -> RegExMatch:
	var regex: RegEx = RegEx.new()
	var error: Error = regex.compile(pattern)
	if error != OK:
		push_error("Cannot compile regex: %s" % pattern)
		return null
	return regex.search(text)


static func createFileLookup(filePaths: PackedStringArray) -> Dictionary:
	var fileByBaseName: Dictionary = {}
	for filePath: String in filePaths:
		fileByBaseName[filePath.get_file().get_basename().to_lower()] = filePath
	return fileByBaseName


static func findFilesRecursive(folderPath: String, extension: String) -> PackedStringArray:
	var filePaths: PackedStringArray = []
	appendFilesRecursive(folderPath, extension.to_lower(), filePaths)
	return filePaths


static func appendFilesRecursive(folderPath: String, extension: String, filePaths: PackedStringArray) -> void:
	var directory: DirAccess = DirAccess.open(folderPath)
	if directory == null:
		push_warning("Cannot open folder while searching files: %s" % folderPath)
		return

	directory.list_dir_begin()
	var fileName: String = directory.get_next()
	while not fileName.is_empty():
		if directory.current_is_dir():
			if not fileName.begins_with("."):
				appendFilesRecursive(folderPath.path_join(fileName), extension, filePaths)
		elif fileName.get_extension().to_lower() == extension:
			filePaths.append(folderPath.path_join(fileName))
		fileName = directory.get_next()
	directory.list_dir_end()


static func readTextFile(filePath: String) -> String:
	var file: FileAccess = FileAccess.open(filePath, FileAccess.READ)
	if file == null:
		push_warning("Cannot read file: %s" % filePath)
		return ""

	var text: String = file.get_as_text()
	file.close()
	return text


static func writeTextFile(filePath: String, text: String, label: String) -> bool:
	var file: FileAccess = FileAccess.open(filePath, FileAccess.WRITE)
	if file == null:
		push_error("Cannot write %s script: %s" % [label, filePath])
		return false

	file.store_string(text)
	file.close()
	return true


static func createFriendlyConfigName(configName: String) -> String:
	var parts: PackedStringArray = configName.split("_", false)
	if parts.size() >= 2:
		var moduleName: String = parts[parts.size() - 2]
		var lastPart: String = parts[parts.size() - 1]
		if lastPart.begins_with("tb") and lastPart.length() > 2:
			lastPart = lastPart.substr(2, lastPart.length() - 2)
		var singularModuleName: String = moduleName.trim_suffix("s")
		if not singularModuleName.is_empty() and lastPart.begins_with(singularModuleName) and lastPart.length() > singularModuleName.length():
			return "%s_%s" % [singularModuleName, lastPart.substr(singularModuleName.length(), lastPart.length() - singularModuleName.length())]
		return lastPart

	return configName


static func sanitizeConstantName(configName: String) -> String:
	var result: String = ""
	var shouldCapitalizeNext: bool = false
	for index: int in range(configName.length()):
		var character: String = configName.substr(index, 1)
		if character == "_":
			shouldCapitalizeNext = true
		elif isIdentifierCharacter(character):
			if shouldCapitalizeNext:
				result += character.to_upper()
				shouldCapitalizeNext = false
			else:
				result += character
		else:
			shouldCapitalizeNext = true

	if result.is_empty():
		result = "config"

	result = result.substr(0, 1).to_lower() + result.substr(1, result.length() - 1)
	if result.substr(0, 1).is_valid_int():
		result = "config_%s" % result

	if not result.is_valid_identifier():
		result = "config_%s" % result.md5_text()

	return result


static func isIdentifierCharacter(character: String) -> bool:
	if character == "_":
		return true

	var code: int = character.unicode_at(0)
	return (code >= 48 and code <= 57) \
		or (code >= 65 and code <= 90) \
		or (code >= 97 and code <= 122)


static func ensureOutputDirectory(outputScriptPath: String) -> bool:
	var outputDirectory: String = outputScriptPath.get_base_dir()
	var absoluteOutputDirectory: String = ProjectSettings.globalize_path(outputDirectory)
	if DirAccess.dir_exists_absolute(absoluteOutputDirectory):
		return true

	var error: Error = DirAccess.make_dir_recursive_absolute(absoluteOutputDirectory)
	if error != OK:
		push_error("Cannot create output directory: %s error: %s" % [outputDirectory, error])
		return false

	return true
