@tool
class_name LubanConfigNameGenerator
extends RefCounted


const defaultConfigDirectory: String = "res://Game/Cd_ProjectZero/Assets/Configs/GameConfigs"
const defaultOutputScriptPath: String = "res://Game/Cd_ProjectZero/Scripts/Gameplay/Config/TbCfg.gd"
const defaultClassName: String = "TbCfg"
const defaultAutoGenDirectory: String = "res://Game/Cd_ProjectZero/Scripts/Mono/Luban/Configs/AutoGen"
const defaultFieldOutputScriptPath: String = "res://Game/Cd_ProjectZero/Scripts/Gameplay/Config/TbField.gd"
const defaultFieldClassName: String = "TbField"
const defaultLoaderOutputDirectory: String = "res://Game/Cd_ProjectZero/Scripts/Gameplay/Config/Loaders"
const configFileExtension: String = "bytes"
const csharpFileExtension: String = "cs"
const loaderFileExtension: String = "gd"


static func generate(
	configDirectory: String = defaultConfigDirectory,
	outputScriptPath: String = defaultOutputScriptPath,
	className: String = defaultClassName,
	autoGenDirectory: String = defaultAutoGenDirectory,
	fieldOutputScriptPath: String = defaultFieldOutputScriptPath,
	fieldClassName: String = defaultFieldClassName,
	loaderOutputDirectory: String = defaultLoaderOutputDirectory
) -> bool:
	var configNames: PackedStringArray = getConfigNames(configDirectory)
	if configNames.is_empty():
		push_error("No Luban config data files found in: %s" % configDirectory)
		return false

	configNames.sort()
	var scriptText: String = createScriptText(configNames, configDirectory, className)
	if not ensureOutputDirectory(outputScriptPath):
		return false

	if not writeTextFile(outputScriptPath, scriptText, "Luban config names"):
		return false

	if not generateFieldNames(configNames, autoGenDirectory, fieldOutputScriptPath, fieldClassName):
		return false

	print("Generated Luban config names: %s (%s configs)" % [outputScriptPath, configNames.size()])

	generateLoaderSkeletons(configNames, loaderOutputDirectory)
	return true


static func getConfigNames(configDirectory: String = defaultConfigDirectory) -> PackedStringArray:
	var names: PackedStringArray = []
	var directory: DirAccess = DirAccess.open(configDirectory)
	if directory == null:
		push_error("Cannot open Luban config directory: %s" % configDirectory)
		return names

	directory.list_dir_begin()
	var fileName: String = directory.get_next()
	while not fileName.is_empty():
		if not directory.current_is_dir() and fileName.get_extension().to_lower() == configFileExtension:
			names.append(fileName.get_basename())
		fileName = directory.get_next()
	directory.list_dir_end()
	return names


static func createScriptText(configNames: PackedStringArray, configDirectory: String, className: String) -> String:
	var usedConstantNames: Dictionary = {}
	var constantLines: Array[String] = []
	var allNameLines: Array[String] = []

	for configName: String in configNames:
		var constantName: String = createUniqueConstantName(configName, usedConstantNames)
		constantLines.append("const %s: StringName = &\"%s\"" % [constantName, configName])
		allNameLines.append("\t%s," % constantName)

	var lines: Array[String] = [
		"# This file is generated by LubanConfigNameGenerator.gd.",
		"# Source: %s" % configDirectory,
		"# Do not edit manually.",
		"",
		"class_name %s" % className,
		"extends RefCounted",
		"",
	]
	lines.append_array(constantLines)
	lines.append("")
	lines.append("const allConfigNames: Array[StringName] = [")
	lines.append_array(allNameLines)
	lines.append("]")
	lines.append("")
	lines.append("")
	lines.append("static func hasConfigName(configName: StringName) -> bool:")
	lines.append("\treturn configName in allConfigNames")
	lines.append("")
	return "\n".join(lines)


static func generateFieldNames(configNames: PackedStringArray, autoGenDirectory: String, fieldOutputScriptPath: String, fieldClassName: String) -> bool:
	var csharpFiles: PackedStringArray = findFilesRecursive(autoGenDirectory, csharpFileExtension)
	if csharpFiles.is_empty():
		push_error("No Luban C# AutoGen files found in: %s" % autoGenDirectory)
		return false

	var fileByBaseName: Dictionary = createFileLookup(csharpFiles)
	var tableFieldInfos: Array[Dictionary] = []

	for configName: String in configNames:
		var tableClassName: String = getTableClassName(configName, fileByBaseName)
		if tableClassName.is_empty():
			push_warning("Cannot find Luban table class for config: %s" % configName)
			continue

		var tableFilePath: String = String(fileByBaseName[tableClassName.to_lower()])
		var tableScriptText: String = readTextFile(tableFilePath)
		var rowClassName: String = getRowClassName(tableScriptText)
		if rowClassName.is_empty():
			push_warning("Cannot find Luban row class for table: %s" % tableClassName)
			continue

		var rowFileKey: String = rowClassName.to_lower()
		if not fileByBaseName.has(rowFileKey):
			push_warning("Cannot find Luban row file for class: %s" % rowClassName)
			continue

		var rowFilePath: String = String(fileByBaseName[rowFileKey])
		var rowScriptText: String = readTextFile(rowFilePath)
		var fieldInfos: Array = getRowFieldInfos(rowScriptText)
		if fieldInfos.is_empty():
			push_warning("Cannot find Luban row fields for class: %s" % rowClassName)
			continue

		tableFieldInfos.append({
			"configName": configName,
			"className": createFieldInnerClassName(configName),
			"fieldInfos": fieldInfos,
		})

	if tableFieldInfos.is_empty():
		push_error("No Luban field names could be generated from: %s" % autoGenDirectory)
		return false

	var scriptText: String = createFieldScriptText(tableFieldInfos, autoGenDirectory, fieldClassName)
	if not ensureOutputDirectory(fieldOutputScriptPath):
		return false

	if not writeTextFile(fieldOutputScriptPath, scriptText, "Luban field names"):
		return false

	print("Generated Luban field names: %s (%s tables)" % [fieldOutputScriptPath, tableFieldInfos.size()])
	return true


static func createFieldScriptText(tableFieldInfos: Array[Dictionary], autoGenDirectory: String, fieldClassName: String) -> String:
	var lines: Array[String] = [
		"# This file is generated by LubanConfigNameGenerator.gd.",
		"# Source: %s" % autoGenDirectory,
		"# Do not edit manually.",
		"",
		"class_name %s" % fieldClassName,
		"extends RefCounted",
		"",
	]

	for tableInfo: Dictionary in tableFieldInfos:
		var configName: String = String(tableInfo["configName"])
		var className: String = String(tableInfo["className"])
		var fieldInfos: Array = tableInfo["fieldInfos"]
		var usedConstantNames: Dictionary = {}
		var allFieldLines: Array[String] = []

		## fieldName -> constantName mapping for Row class generation
		var nameToConstant: Dictionary = {}

		lines.append("class %s:" % className)
		lines.append("\tconst table: StringName = &\"%s\"" % configName)

		for info: Dictionary in fieldInfos:
			var fieldName: String = String(info["name"])
			var constantName: String = createUniqueName(sanitizeConstantName(fieldName), usedConstantNames)
			nameToConstant[fieldName] = constantName
			lines.append("\tconst %s: StringName = &\"%s\"" % [constantName, fieldName])
			allFieldLines.append("\t\t%s," % constantName)

		lines.append("")
		lines.append("\tconst allFieldNames: Array[StringName] = [")
		lines.append_array(allFieldLines)
		lines.append("\t]")
		lines.append("")
		lines.append("")
		lines.append("\tstatic func hasFieldName(fieldName: StringName) -> bool:")
		lines.append("\t\treturn fieldName in allFieldNames")

		## Generate typed Row inner class
		lines.append("")
		lines.append("")
		appendRowClass(lines, fieldInfos, nameToConstant, "\t")

		lines.append("")

	return "\n".join(lines)


#region Type Mapping (C# → GDScript)

## Returns the GDScript type hint string for a C# field type.
static func getGdTypeForCsType(csType: String) -> String:
	var normalized: String = csType.strip_edges()
	if isStringType(normalized):
		return "String"
	if isIntType(normalized):
		return "int"
	if isFloatType(normalized):
		return "float"
	if isBoolType(normalized):
		return "bool"
	if isArrayType(normalized):
		return "Array"
	return "Variant"


## Returns the GDScript default value literal for a C# field type.
static func getDefaultValueForCsType(csType: String) -> String:
	var normalized: String = csType.strip_edges()
	if isStringType(normalized):
		return "\"\""
	if isIntType(normalized):
		return "0"
	if isFloatType(normalized):
		return "0.0"
	if isBoolType(normalized):
		return "false"
	if isArrayType(normalized):
		return "[]"
	return "null"


## Returns the GDScript conversion expression for a C# field type.
## The expression operates on a local variable named `v` (Variant).
static func getConversionForCsType(csType: String) -> String:
	var normalized: String = csType.strip_edges()
	if isStringType(normalized):
		return "str(v)"
	if isIntType(normalized):
		return "int(v)"
	if isFloatType(normalized):
		return "float(v)"
	if isBoolType(normalized):
		return "bool(v)"
	if isArrayType(normalized):
		return "Array(v) if v is Array else ([] if v == null else [v])"
	return "v"


static func isStringType(normalized: String) -> bool:
	return normalized == "string"


static func isIntType(normalized: String) -> bool:
	return normalized in ["int", "long", "short", "byte", "uint", "ulong", "ushort"]


static func isFloatType(normalized: String) -> bool:
	return normalized in ["float", "double", "decimal"]


static func isBoolType(normalized: String) -> bool:
	return normalized == "bool"


static func isArrayType(normalized: String) -> bool:
	return normalized.ends_with("[]") or normalized.begins_with("list<") or normalized.begins_with("list")

#endregion


## Appends a typed Row inner class for one table's field constants.
static func appendRowClass(lines: Array[String], fieldInfos: Array, nameToConstant: Dictionary, indent: String) -> void:
	var i: String = indent
	var i2: String = indent + "\t"
	var i3: String = indent + "\t\t"

	lines.append("%sclass Row:" % i)
	lines.append("%svar data: Dictionary" % i2)
	lines.append("")
	lines.append("")
	lines.append("%sfunc _init(rowData: Dictionary = {}) -> void:" % i2)
	lines.append("%sdata = rowData" % i3)

	## DEFAULT_ROW constant with typed defaults per field
	lines.append("")
	lines.append("")
	lines.append("%sconst DEFAULT_ROW: Dictionary = {" % i2)
	for info: Dictionary in fieldInfos:
		var fieldName: String = String(info["name"])
		var csType: String = String(info["csType"])
		var defaultValue: String = getDefaultValueForCsType(csType)
		lines.append("%s&\"%s\": %s," % [i3, fieldName, defaultValue])
	lines.append("%s}" % i2)

	## Typed getter for each field — uses string literal keys
	## because GDScript inner classes cannot access outer class constants
	for info: Dictionary in fieldInfos:
		var fieldName: String = String(info["name"])
		var csType: String = String(info["csType"])
		var gdType: String = getGdTypeForCsType(csType)
		var conversion: String = getConversionForCsType(csType)
		var methodName: String = "get%s" % fieldName.substr(0, 1).to_upper() + fieldName.substr(1)

		lines.append("")
		lines.append("")
		lines.append("%sfunc %s() -> %s:" % [i2, methodName, gdType])
		lines.append("%svar v: Variant = data.get(&\"%s\", DEFAULT_ROW[&\"%s\"])" % [i3, fieldName, fieldName])
		lines.append("%sreturn %s" % [i3, conversion])


#region Loader Skeleton Generation

## Generates a Loader skeleton .gd file for each config table.
## Skips tables that already have a Loader file (never overwrites).
static func generateLoaderSkeletons(configNames: PackedStringArray, outputDirectory: String) -> void:
	if not ensureOutputDirectory(outputDirectory + "/dummy"):
		return

	var existingFiles: PackedStringArray = findFilesRecursive(outputDirectory, loaderFileExtension)
	var existingBaseNames: Dictionary = {}
	for filePath: String in existingFiles:
		existingBaseNames[filePath.get_file().get_basename().to_lower()] = true

	var generatedCount: int = 0
	for configName: String in configNames:
		var loaderClassName: String = createLoaderClassName(configName)
		var fieldClassName: String = createFieldInnerClassName(configName)
		var fileName: String = "%s.gd" % loaderClassName

		if existingBaseNames.has(fileName.get_basename().to_lower()):
			continue

		var scriptText: String = createLoaderSkeletonText(loaderClassName, fieldClassName, configName)
		var filePath: String = outputDirectory.path_join(fileName)
		if writeTextFile(filePath, scriptText, "Luban loader skeleton"):
			generatedCount += 1

	if generatedCount > 0:
		print("Generated %s Luban loader skeleton(s) in: %s" % [generatedCount, outputDirectory])


## Creates a PascalCase loader class name from a config name.
## E.g. "identity_tbidentityeffectpilot" → "LubanIdentityEffectPilotLoader"
static func createLoaderClassName(configName: String) -> String:
	var parts: PackedStringArray = configName.split("_", false)
	if parts.is_empty():
		return "LubanLoader"
	var tableName: String = parts[parts.size() - 1]
	## Strip "tb" prefix if present
	if tableName.begins_with("tb") and tableName.length() > 2:
		tableName = tableName.substr(2)
	## Convert to PascalCase: split by uppercase runs
	var pascal: String = ""
	var capitalizeNext: bool = true
	for index: int in range(tableName.length()):
		var ch: String = tableName.substr(index, 1)
		if ch == "_":
			capitalizeNext = true
		elif capitalizeNext:
			pascal += ch.to_upper()
			capitalizeNext = false
		else:
			pascal += ch
	return "Luban%sLoader" % pascal


## Creates the skeleton GDScript text for a Loader.
static func createLoaderSkeletonText(loaderClassName: String, fieldClassName: String, configName: String) -> String:
	var lines: Array[String] = [
		"## Auto-generated skeleton for %s." % configName,
		"## Edit convertRow() to map each row to your runtime type.",
		"## This file will NOT be overwritten by the generator once created.",
		"",
		"class_name %s" % loaderClassName,
		"extends RefCounted",
		"",
		"",
		"static func loadAll(tb: Tb) -> Array:",
		"\treturn LubanLoader.loadAll(tb, TbCfg.%s, convertRow)" % sanitizeConstantName(createFriendlyConfigName(configName)),
		"",
		"",
		"static func loadById(tb: Tb, key: Variant) -> Variant:",
		"\treturn LubanLoader.loadFirst(tb, TbCfg.%s, key, convertRow)" % sanitizeConstantName(createFriendlyConfigName(configName)),
		"",
		"",
		"## Override this function to convert each row into your runtime object.",
		"## Use %s.Row for typed field access." % fieldClassName,
		"static func convertRow(row: Dictionary) -> Variant:",
		"\tvar r: %s.Row = %s.Row.new(row)" % [fieldClassName, fieldClassName],
		"\t## TODO: Create your runtime object and populate it from r.",
		"\t## Example:",
		"\t## var obj: MyObject = MyObject.new()",
		"\t## obj.someField = r.getSomeField()",
		"\t## return obj",
		"\treturn r.data",
		"",
	]
	return "\n".join(lines)

#endregion


static func createUniqueConstantName(configName: String, usedConstantNames: Dictionary) -> String:
	var baseName: String = sanitizeConstantName(createFriendlyConfigName(configName))
	return createUniqueName(baseName, usedConstantNames)


static func createUniqueName(baseName: String, usedNames: Dictionary) -> String:
	var constantName: String = baseName
	var suffix: int = 2
	while usedNames.has(constantName):
		constantName = "%s_%s" % [baseName, suffix]
		suffix += 1
	usedNames[constantName] = true
	return constantName


static func createFieldInnerClassName(configName: String) -> String:
	var constantName: String = sanitizeConstantName(createFriendlyConfigName(configName))
	var className: String = constantName.substr(0, 1).to_upper() + constantName.substr(1, constantName.length() - 1)
	if not className.is_valid_identifier() or className.substr(0, 1).is_valid_int():
		className = "Table%s" % className.md5_text()
	return className


static func getTableClassName(configName: String, fileByBaseName: Dictionary) -> String:
	var parts: PackedStringArray = configName.split("_", false)
	if parts.is_empty():
		return ""

	var tableFileKey: String = parts[parts.size() - 1].to_lower()
	if fileByBaseName.has(tableFileKey):
		return String(fileByBaseName[tableFileKey]).get_file().get_basename()

	return ""


static func getRowClassName(tableScriptText: String) -> String:
	var listMatch: RegExMatch = searchRegex(tableScriptText, "List<([A-Za-z0-9_\\.]+)>")
	if listMatch != null:
		return listMatch.get_string(1).get_slice(".", listMatch.get_string(1).get_slice_count(".") - 1)

	var dataMatch: RegExMatch = searchRegex(tableScriptText, "private\\s+readonly\\s+([A-Za-z0-9_\\.]+)\\s+_data")
	if dataMatch != null:
		return dataMatch.get_string(1).get_slice(".", dataMatch.get_string(1).get_slice_count(".") - 1)

	return ""


## Parses C# row class source and extracts field info (name + type).
## Returns Array of Dictionaries with keys: "name" (String), "csType" (String).
static func getRowFieldInfos(rowScriptText: String) -> Array:
	var fieldInfos: Array = []
	var regex: RegEx = RegEx.new()
	var error: Error = regex.compile("public\\s+readonly\\s+([A-Za-z0-9_<>,\\.\\?\\[\\]\\s]+?)\\s+([A-Za-z_][A-Za-z0-9_]*)\\s*;")
	if error != OK:
		push_error("Cannot compile Luban row field regex.")
		return fieldInfos

	for regexMatch: RegExMatch in regex.search_all(rowScriptText):
		var typeAndName: String = regexMatch.get_string(1).strip_edges()
		var fieldName: String = regexMatch.get_string(2)
		var csType: String = splitTypeFromDeclaration(typeAndName)
		fieldInfos.append({"name": fieldName, "csType": csType})

	return fieldInfos


## Extracts the C# type from a type declaration string.
## E.g. "System.Collections.Generic.List<string> _v" → "List<string>"
## E.g. "string" → "string"
static func splitTypeFromDeclaration(typeAndName: String) -> String:
	var trimmed: String = typeAndName.strip_edges()
	## Find the last space that separates the type from a name
	var lastSpace: int = trimmed.rfind(" ")
	if lastSpace <= 0:
		return trimmed
	var typePart: String = trimmed.substr(0, lastSpace).strip_edges()
	## Simplify: take only the last part of namespace-qualified types
	var lastDot: int = typePart.rfind(".")
	if lastDot >= 0:
		typePart = typePart.substr(lastDot + 1)
	## Strip nullable suffix
	if typePart.ends_with("?"):
		typePart = typePart.substr(0, typePart.length() - 1)
	return typePart.to_lower()


static func searchRegex(text: String, pattern: String) -> RegExMatch:
	var regex: RegEx = RegEx.new()
	var error: Error = regex.compile(pattern)
	if error != OK:
		push_error("Cannot compile regex: %s" % pattern)
		return null
	return regex.search(text)


static func createFileLookup(filePaths: PackedStringArray) -> Dictionary:
	var fileByBaseName: Dictionary = {}
	for filePath: String in filePaths:
		fileByBaseName[filePath.get_file().get_basename().to_lower()] = filePath
	return fileByBaseName


static func findFilesRecursive(folderPath: String, extension: String) -> PackedStringArray:
	var filePaths: PackedStringArray = []
	appendFilesRecursive(folderPath, extension.to_lower(), filePaths)
	return filePaths


static func appendFilesRecursive(folderPath: String, extension: String, filePaths: PackedStringArray) -> void:
	var directory: DirAccess = DirAccess.open(folderPath)
	if directory == null:
		push_warning("Cannot open folder while searching files: %s" % folderPath)
		return

	directory.list_dir_begin()
	var fileName: String = directory.get_next()
	while not fileName.is_empty():
		if directory.current_is_dir():
			if not fileName.begins_with("."):
				appendFilesRecursive(folderPath.path_join(fileName), extension, filePaths)
		elif fileName.get_extension().to_lower() == extension:
			filePaths.append(folderPath.path_join(fileName))
		fileName = directory.get_next()
	directory.list_dir_end()


static func readTextFile(filePath: String) -> String:
	var file: FileAccess = FileAccess.open(filePath, FileAccess.READ)
	if file == null:
		push_warning("Cannot read file: %s" % filePath)
		return ""

	var text: String = file.get_as_text()
	file.close()
	return text


static func writeTextFile(filePath: String, text: String, label: String) -> bool:
	var file: FileAccess = FileAccess.open(filePath, FileAccess.WRITE)
	if file == null:
		push_error("Cannot write %s script: %s" % [label, filePath])
		return false

	file.store_string(text)
	file.close()
	return true


static func createFriendlyConfigName(configName: String) -> String:
	var parts: PackedStringArray = configName.split("_", false)
	if parts.size() >= 2:
		var moduleName: String = parts[parts.size() - 2]
		var lastPart: String = parts[parts.size() - 1]
		if lastPart.begins_with("tb") and lastPart.length() > 2:
			lastPart = lastPart.substr(2, lastPart.length() - 2)
		var singularModuleName: String = moduleName.trim_suffix("s")
		if not singularModuleName.is_empty() and lastPart.begins_with(singularModuleName) and lastPart.length() > singularModuleName.length():
			return "%s_%s" % [singularModuleName, lastPart.substr(singularModuleName.length(), lastPart.length() - singularModuleName.length())]
		return lastPart

	return configName


static func sanitizeConstantName(configName: String) -> String:
	var result: String = ""
	var shouldCapitalizeNext: bool = false
	for index: int in range(configName.length()):
		var character: String = configName.substr(index, 1)
		if character == "_":
			shouldCapitalizeNext = true
		elif isIdentifierCharacter(character):
			if shouldCapitalizeNext:
				result += character.to_upper()
				shouldCapitalizeNext = false
			else:
				result += character
		else:
			shouldCapitalizeNext = true

	if result.is_empty():
		result = "config"

	result = result.substr(0, 1).to_lower() + result.substr(1, result.length() - 1)
	if result.substr(0, 1).is_valid_int():
		result = "config_%s" % result

	if not result.is_valid_identifier():
		result = "config_%s" % result.md5_text()

	return result


static func isIdentifierCharacter(character: String) -> bool:
	if character == "_":
		return true

	var code: int = character.unicode_at(0)
	return (code >= 48 and code <= 57) \
		or (code >= 65 and code <= 90) \
		or (code >= 97 and code <= 122)


static func ensureOutputDirectory(outputScriptPath: String) -> bool:
	var outputDirectory: String = outputScriptPath.get_base_dir()
	var absoluteOutputDirectory: String = ProjectSettings.globalize_path(outputDirectory)
	if DirAccess.dir_exists_absolute(absoluteOutputDirectory):
		return true

	var error: Error = DirAccess.make_dir_recursive_absolute(absoluteOutputDirectory)
	if error != OK:
		push_error("Cannot create output directory: %s error: %s" % [outputDirectory, error])
		return false

	return true
