
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Concurrent;
using Luban;


namespace Y0Studio.Config.Examples
{
    public sealed partial class ExampleSingleton : Luban.BeanBase
    {
        public ExampleSingleton(ByteBuf _buf) 
        {
            NewbieDiscountTimes = _buf.ReadInt();
            AffectionIncrementLimit = _buf.ReadFloat();
            GiftCooldown = _buf.ReadLong();

            PostInit();
        }

        public static ExampleSingleton DeserializeExampleSingleton(ByteBuf _buf)
        {
            return new Examples.ExampleSingleton(_buf);
        }

        /// <summary>
        /// 新手商店优惠次数
        /// </summary>
        public readonly int NewbieDiscountTimes;
        /// <summary>
        /// 单日好感度增加上限
        /// </summary>
        public readonly float AffectionIncrementLimit;
        /// <summary>
        /// 礼物冷却时间
        /// </summary>
        public readonly long GiftCooldown;
    
        public const int __ID__ = 209511622;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(ConcurrentDictionary<Type, IConfigSingleton> tables)
        {

            PostResolve();
        }

        public override string ToString()
        {
            return "{ "
            + "newbieDiscountTimes:" + NewbieDiscountTimes + ","
            + "affectionIncrementLimit:" + AffectionIncrementLimit + ","
            + "giftCooldown:" + GiftCooldown + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolve();
    }
}

