
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Concurrent;
using Luban;


namespace Y0Studio.Config.Examples
{
    public sealed partial class ExampleBasic : Luban.BeanBase
    {
        public ExampleBasic(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Grade = _buf.ReadInt();
            IconRes = _buf.ReadString();
            Price = _buf.ReadFloat();
            Type = (EExampleType)_buf.ReadInt();
            IsInGacha = _buf.ReadBool();
            SomeLongValue = _buf.ReadLong();
            SomeDoubleValue = _buf.ReadDouble();

            PostInit();
        }

        public static ExampleBasic DeserializeExampleBasic(ByteBuf _buf)
        {
            return new Examples.ExampleBasic(_buf);
        }

        /// <summary>
        /// 这是Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 等级
        /// </summary>
        public readonly int Grade;
        /// <summary>
        /// 图标资源
        /// </summary>
        public readonly string IconRes;
        /// <summary>
        /// 价格
        /// </summary>
        public readonly float Price;
        /// <summary>
        /// 类型
        /// </summary>
        public readonly EExampleType Type;
        /// <summary>
        /// 是否可抽取
        /// </summary>
        public readonly bool IsInGacha;
        /// <summary>
        /// 这是一个long
        /// </summary>
        public readonly long SomeLongValue;
        /// <summary>
        /// 这是一个double
        /// </summary>
        public readonly double SomeDoubleValue;
    
        public const int __ID__ = -717891991;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(ConcurrentDictionary<Type, IConfigSingleton> tables)
        {

            PostResolve();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "name:" + Name + ","
            + "grade:" + Grade + ","
            + "iconRes:" + IconRes + ","
            + "price:" + Price + ","
            + "type:" + Type + ","
            + "isInGacha:" + IsInGacha + ","
            + "someLongValue:" + SomeLongValue + ","
            + "someDoubleValue:" + SomeDoubleValue + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolve();
    }
}

