
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Concurrent;
using Luban;


namespace Y0Studio.Config.Examples
{
    [Config]
    public partial class TbExampleList : ConfigSingleton<TbExampleList>
    {
        private readonly System.Collections.Generic.List<Examples.ExampleList> _dataList;


        public TbExampleList(ByteBuf _buf)
        {
            _dataList = new System.Collections.Generic.List<Examples.ExampleList>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                Examples.ExampleList _v;
                _v = global::Y0Studio.Config.Examples.ExampleList.DeserializeExampleList(_buf);
                _dataList.Add(_v);
            }
            PostInit();
        }

        public System.Collections.Generic.List<Examples.ExampleList> DataList => _dataList;

        
        public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
        {
            foreach (var _v in _dataList)
            {
                _v.ResolveRef(_tables);
            }
            PostResolve();
        }

        public override void TranslateText(Func<string, string, string> translator)
        {
            throw new NotImplementedException();
        }
        partial void PostInit();
        partial void PostResolve();
    }

}

